#ifndef _vibrational_indexing_h_
#define _vibrational_indexing_h_

/*! \file vibrational_indexing.h 
\ingroup METHODS
\brief methods for iterating/indexing vibrational states with the same number of vibrational quanta
*/

#include "genincludes.h"
#include "mathutil.h"
#include "constants.h"
#include "kmatrix.h"


//! get a next vibrational state (norm_modes -- number of normal modes, max_excitations -- totoal max number of vibr quanta in all normal modes)
bool enumerateVibrStates(int norm_modes, int max_excitations, std::vector <int>& state, const bool if_comb_bands);
/*!
 (to initialize (generate first population of the vibrational states) make state[0] negative)

 Example:
 norm_modes=5, max_excitations=7;  "state"=[2,1,3,0,1] ("see stars and bars" problem)
 "state" contains number of "stars" (excitations for each normal mode) in each bin [2,1,3,0,1]: **|*|***||*
 "combination" contains position of the "bars" (in modified set -- plus one star in each bin) [2,4,8,9]:***|**|****|*|**
 this util. (1)converts "state"->"combination" 
            (2)calculates the next "combination" using enumerateCombinations(n,k,comb) (ennumerates combinations, total number = C_n^k)
            (3)converts "combination"->"state"
*/


//! returns tbe position of the "state" in the list of states generated by enumerateVibrStates() iterator function (for a given total number of excitations and number of normal modes)
//! N -- size of the 'state' vector
//! k -- total number of excitation quanta in the 'state'
// ZZZ 4/11/2012 removed, and the combinations are calculated now on the fly
//unsigned long convVibrState2Index(std::vector <int>& state, int N, unsigned long * C, int k);
unsigned long convVibrState2Index(std::vector <int>& state, int N, int k);



/*!
  state -- vector with quantum numbers; length N; K--total maximum number of excitations (summ of all elements)
  starts from the left "digit"=state[0]; calculates how many states of length (N-1) with (K-state[0]) exists = C_([N-1]-1)^([K-state[0]]+[N-1]-1)
  goes recursively though all "digist" down the list
*/

//! not implemented yet 
void convIndex2VibrState(unsigned long index, std::vector <int>& state);

#endif
